import {StyleSheet} from 'react-native';
import {colors, fontType} from '../../theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background(),
  },
  bannerContainer: {
    backgroundColor: colors.banner(),
    position: 'relative',
  },
  horizontalScroll: {
    position: 'absolute',
    top: 190,
    left: -10,
    right: 0,
    zIndex: 10,
  },
  horizontalCardContainer: {
    flexDirection: 'row',
    flex: 1,
  },
  horizontalCard: {
    width: 230,
    height: 80,
    marginLeft: 20,
    backgroundColor: colors.background(),
    borderWidth: 0.5,
    borderColor: colors.primary(),
    borderRadius: 18,
    padding: 10,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.black(),
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  horizontalText: {
    fontSize: 14,
    fontFamily: fontType['Poppins-SemiBold'],
    color: colors.textDark(),
    marginRight: 15,
    marginTop: 10,
  },
  horizontalDesk: {
    fontSize: 8,
    fontFamily: fontType['Poppins-SemiBold'],
    color: colors.textLight(),
  },
  arrow: {
    marginTop: 19,
    marginRight: 0,
  },
  innerCurve: {
    position: 'absolute',
    borderWidth: 0.5,
    borderColor: colors.primary(),
    left: 44,
    width: 20,
    height: 20,
    backgroundColor: colors.background(),
    borderRadius: 50,
    zIndex: 20,
  },
  garis: {
    position: 'absolute',
    left: -14,
    backgroundColor: colors.border(),
    width: 3,
    height: 8,
    borderRadius: 50,
  },
  bannerImage: {
    width: '100%',
    height: 220,
    borderRadius: 0,
  },
  content: {
    paddingHorizontal: 10,
    marginTop: 50,
  },
  serviceList: {
    backgroundColor: colors.white(),
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 20,
    marginVertical: 20,
    shadowColor: colors.black(),
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 15,
  },
  saldo: {
    fontSize: 17,
    fontFamily: fontType['Poppins-Bold'],
    color: colors.black(),
    margin: 0,
  },
  voucher: {
    fontSize: 10,
    fontFamily: fontType['Poppins-Medium'],
    color: colors.textDark(),
    margin: 0,
  },
  rightContainer: {
    marginLeft: 'auto',
    flexDirection: 'row',
    gap: 15,
  },
  iconContainer: {
    alignItems: 'center',
    alignSelf: 'flex-end',
  },
  label: {
    fontSize: 12,
    fontFamily: fontType['Poppins-SemiBold'],
    color: colors.black(),
  },
  row: {
    justifyContent: 'space-between',
  },
  serviceCard: {
    backgroundColor: colors.white(),
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
    width: '48%',
    marginBottom: 15,
    shadowColor: colors.black(),
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  serviceText: {
    fontSize: 16,
    fontFamily: fontType['Poppins-SemiBold'],
    color: colors.textDark(),
    marginTop: 10,
  },
  button: {
    height: 22,
    backgroundColor: colors.primary(),
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 5,
    alignItems: 'center',
    marginTop: 18,
  },
  buttonText: {
    color: colors.white(),
    fontSize: 8,
    fontFamily: fontType['Poppins-SemiBold'],
  },
});

export default styles;
